const MONGODB_DATABASE_NAME = 'sample_mflix';
const MONGODB_COLLECTION_NAME = 'movies';
const MONGODB_SEARCH_INDEX_NAME = 'default';
const BEDROCK_MODEL_ID = 'amazon.titan-embed-text-v1';

export {
  BEDROCK_MODEL_ID,
  MONGODB_COLLECTION_NAME,
  MONGODB_DATABASE_NAME,
  MONGODB_SEARCH_INDEX_NAME,
};
